site_name: P-Shaker
theme:
  name: material
  logo: images/logo1.jpg  # Ruta de tu nuevo ícono
  palette:
    scheme: slate  # Modo oscuro
    primary: deep orange  # Cambia el color principal (verde en este caso)
    accent: orange  # Cambia el color de acento

nav:
  - Getting Started: index.md
  - Technical Specifications: specs.md
  - Assembly Installation: install.md
  - Product Usage: usage.md
  - Maintenance and Troubleshooting: maintenance.md
  - Development and Extensibility: dev.md
  - Safety: safety.md
  - Contact and Support: support.md
  - Purchase One: buy.md

